services:
  caddy_preview:
    image: caddy:2
    container_name: salafi_caddy_preview
    restart: unless-stopped
    env_file:
      - ./envs/.env.preview
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile.preview:/etc/caddy/Caddyfile:ro
      - caddy_preview_data:/data
      - caddy_preview_config:/config
    networks:
      - salafi_net

volumes:
  caddy_preview_data:
  caddy_preview_config:
